name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper (safety)
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Installs the Android SDK and puts sdkmanager on PATH
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Accept all Android SDK licenses (this removes the “licenses not accepted” error)
      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      # Install exactly the platform + tools we build against
      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build your debug APK
      - name: Build Debug APK
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      # (Optional) List artifacts for easier debugging
      - name: List build outputs
        run: ls -R app/build/outputs || true

      # Upload every APK we produced
      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/**/*.apk
