name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        run: |
          set -e
          ANDROID_SDK_ROOT="$HOME/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"

          curl -sSL -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q sdk.zip
          rm sdk.zip

          mv cmdline-tools latest

          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      - name: Accept licenses and install SDK packages
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/licenses"
          cat > "$ANDROID_SDK_ROOT/licenses/android-sdk-license" <<EOF
d56f5187479451eabf01fb78af6dfcb131a6481e
24333f8a63b6825ea9c5514f83c2829b004d1fee
e6b6e5d95f7e3d4e6d9f1f5b0a1b1b6db8b3a7c5
8933bad161af4178b1185d1a37fbf41ea5269c55
EOF

          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: List build outputs
        run: ls -R app/build/outputs || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Build Logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-logs
          path: |
            **/*.log
            **/build/reports/**
          if-no-files-found: ignore
