name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ✅ Official SDK setup action
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: List outputs
        run: ls -R app/build/outputs || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: error

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: app/build/*.log
