name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept SDK licenses
      run: yes | sdkmanager --licenses

    - name: Install required SDK packages
      run: sdkmanager "platforms;android-34" "build-tools;34.0.0"

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: List build outputs
      run: ls -R app/build/outputs || true

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/*.apk
