name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info --refresh-dependencies

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: CapyTap-APKs
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: warn

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: '**/build/*.log'
          if-no-files-found: ignore
