name: Android Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download gradle-wrapper.jar (force overwrite)
        run: |
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/8.7/gradle-wrapper-8.7.jar
          ls -lh gradle/wrapper/

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info --refresh-dependencies

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: CapyTap-APKs
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: warn

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: '**/build/*.log'
          if-no-files-found: ignore
