name: Android Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle 8.7
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Build Debug APK (log to file)
        run: |
          gradle assembleDebug --stacktrace --info --refresh-dependencies > build.log 2>&1 || true

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CapyTap-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: ignore
