name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Try SDK 34 first, if it fails → fallback to SDK 33
      - name: Install Android SDK
        run: |
          set -e
          echo "👉 Trying to install SDK 34..."
          sdkmanager "platforms;android-34" "build-tools;34.0.0" || {
            echo "⚠️ SDK 34 not found, falling back to SDK 33..."
            sdkmanager "platforms;android-33" "build-tools;33.0.2"
          }

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info --refresh-dependencies | tee gradle-build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/**/*.apk

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: gradle-build.log
