name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # First try API 34
      - name: Install Android SDK (try 34)
        id: sdk34
        continue-on-error: true
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0

      # If 34 fails, install API 33
      - name: Install Android SDK (fallback 33)
        if: steps.sdk34.outcome == 'failure'
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-33
            build-tools;33.0.2

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info --refresh-dependencies | tee gradle-build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/**/*.apk

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: gradle-build.log
