name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Step 1: Download Android commandline-tools
      - name: Install Android SDK
        run: |
          ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk.zip -d latest
          rm sdk.zip
          # Persist PATH + ANDROID_SDK_ROOT for later steps
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

      # Step 2: Install SDK components
      - name: Accept licenses and install SDK packages
        run: |
          sdkmanager --version
          yes | sdkmanager --licenses
          sdkmanager \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "platform-tools"

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: List build outputs
        run: ls -R app/build/outputs || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: error

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: app/build/*.log
